KnowledgeHubPortal.Web/Controllers/ArticlesController.cs
using KnowledgeHubPortal.Domain.Entities;
using KnowledgeHubPortal.Domain.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using X.PagedList.Extensions;

namespace KnowledgeHubPortal.Web.Controllers
{
    public class ArticlesController : Controller
    {
        private readonly ICatagoryRepository catagoryRepo;
        private readonly IArticleRepository articleRepo;

        public ArticlesController(ICatagoryRepository catagoryRepo, IArticleRepository articleRepo)
        {
            this.catagoryRepo = catagoryRepo;
            this.articleRepo = articleRepo;
        }
        //public IActionResult Index()
        //{

        //}

        [HttpGet]
        [Authorize]
        public IActionResult Submit()
        {
            var catagories = catagoryRepo.GetAll();

            ViewBag.Categories = catagories;
            //ViewData["Categories"] = catagories;
            //TempData["Categories"] = catagories;

            return View(new Article());
        }

        [HttpPost]
        [Authorize]
        public IActionResult Submit(Article article)
        {
            // validate
            if (!ModelState.IsValid)
            {
                var catagories = catagoryRepo.GetAll();

                ViewBag.Categories = catagories;
                return View(article);
            }

            article.IsApproved = false;
            article.DateSubmited = DateTime.Now;
            article.SubmitedBy = User.Identity.Name ?? "Unknown";


            articleRepo.SubmitArticle(article);
            TempData["MSG"] = $"Article {article.Title} submited successfully for admin review";
            return RedirectToAction("Submit");
        }

        // .../articles/review
        //[HttpGet]
        [Authorize(Roles = "admin")]
        public IActionResult Review(int id = 0)
        {
            // fetch the articles for review
            var articlesForReview = articleRepo.GetArticlesForReview(id);
            var catagories = catagoryRepo.GetAll();

            var selectItems = from catagory in catagories
                              select new SelectListItem
                              {
                                  Text = catagory.Name,
                                  Value = catagory.Id.ToString()
                              };

            ViewBag.Catagories = selectItems;
            // send to view
            return View(articlesForReview);
        }
        [Authorize(Roles = "admin")]
        public IActionResult Approve(List<int> ids)
        {
            articleRepo.ApproveArticles(ids);
            TempData["MSG"] = $"{ids.Count} Articles approved successfully";
            return RedirectToAction("Review");
        }
        [Authorize(Roles = "admin")]
        public IActionResult Reject(List<int> ids)
        {
            articleRepo.RejectArticles(ids);
            TempData["MSG"] = $"{ids.Count} Articles rejected successfully";
            return RedirectToAction("Review");
        }


        // .../Articles/Browse

        // .../Articles/Browse/2025/Venkat
        [AllowAnonymous]
        [Route("Articles/Browse/{year:int}/{submiter:alpha}")]
        public IActionResult Browse(int year, string submiter, int id = 0, int? page = null)
        {

            int pageNumber = page ?? 1;
            int pageSize = 4;


            var catagories = catagoryRepo.GetAll();



            var selectItems = from catagory in catagories
                              select new SelectListItem
                              {
                                  Text = catagory.Name,
                                  Value = catagory.Id.ToString()
                              };

            ViewBag.Catagories = selectItems;

            var articlesForBrowse = articleRepo.GetArticlesForBrowse(id)
                .Where(a => a.SubmitedBy.Contains(submiter) && a.DateSubmited.Year == year)
                .OrderBy(a => a.ArticleId);

            var pagedList = articlesForBrowse.ToPagedList(pageNumber, pageSize);


            return View(pagedList);
        }

    }
}

KnowledgeHubPortal.Web/Controllers/CatagoryController.cs
using KnowledgeHubPortal.Domain.Entities;
using KnowledgeHubPortal.Domain.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace KnowledgeHubPortal.Web.Controllers
{
    [Authorize(Roles = "admin")]
    public class CatagoryController : Controller
    {
        //CatagoryRepository catagoryRepository = new CatagoryRepository();
        private ICatagoryRepository _repository;


        public CatagoryController(ICatagoryRepository repository)
        {
            this._repository = repository;
        }

        // .../catagory/index
        [ResponseCache(Duration = 60)]
        // [AllowAnonymous]
        public async Task<IActionResult> Index()
        {

            ViewBag.Date = DateTime.Now;

            // Fetch the data from model

            //CatagoryRepository catagoryRepository = new CatagoryRepository();

            //var catagories = _repository.GetAll();

            //List<Catagory> catagories = new List<Catagory>()
            //{
            //    new Catagory{Id=111, Name = "Sports", Description="Sports related articles" },
            //    new Catagory{Id=222, Name = "Education", Description="Education related articles" },
            //    new Catagory{Id=333, Name = ".Net", Description=".Net related articles" },
            //    new Catagory{Id=444, Name = "MVC", Description="MVC related articles" },
            //    new Catagory{Id=555, Name = "AI", Description="AI related articles" }
            //};

            // pass the data to view

            //int pageSize = 5;
            //int pageNumber = page ?? 1;

            var categories = _repository.GetAllAsync().Result;//.Result.OrderBy(c => c.Name);

            //var pagedList = categories.ToPagedList(pageNumber, pageSize);

            return View(categories);
        }
        // .../catagory/create
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Catagory catagory)
        {
            // collect the data from ui
            // validate
            if (!ModelState.IsValid)
            {
                return View();
            }
            // pass to backend
            await _repository.SaveAsync(catagory);
            // return a view
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id)
        {
            await _repository.DeleteAsync(id);

            TempData["MSG"] = $"Category {id} successfully deleted";


            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            // fetch the all data based on id
            Catagory category = await _repository.GetByIdAsync(id);
            // return edit view
            return View(category);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Catagory catagory)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            await _repository.EditAsync(catagory);
            TempData["MSG"] = $"Category {catagory.Id} successfully updated";
            return RedirectToAction("Index");
        }
    }
}

KnowledgeHubPortal.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KnowledgeHubPortal.Web</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/KnowledgeHubPortal.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">Knowledge Hub Portal</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Catagory" asp-action="Index">Manage Catagory</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Articles" asp-action="Submit">Submit Articles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Articles" asp-action="Review">Review Articles</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Articles" asp-action="Browse">Browse Articles</a>
                        </li>


                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Knowledge Hub Portal - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

KnowledgeHubPortal.Web/Views/Shared/_MyLayout.cshtml
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
</head>
<body>
    @RenderSection("S2",false)
    <h1>This is title</h1>
    <hr />
    @RenderBody()
<hr />
<footer>This is footer</footer>

    @RenderSection("S1",false)

</body>
</html>

KnowledgeHubPortal.Web/Views/Shared/_SearchArticlesPartial.cshtml
    <div class="col-auto">
        <select name="id" class="form-select" asp-items="@ViewBag.Catagories">
            <option disabled selected>Select a category</option>
        </select>
    </div>
    <div class="col-auto">
        <input type="submit" name="btnSubmit" value="Search" class="btn btn-outline-primary" />
    </div>